services:
  nestapp:
    container_name: nestapp
    image: mks/nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - JWT_SECRET=b8cfcc9590927546c9dbf97ccc5b32b0f038ce37d39e82c058bacb7615f85e25
    depends_on:
      - db  
      - redis
    volumes:
      - ./src:/app/src
  redis:
    container_name: cache
    image: redis:6
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - redis:/data
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  redis:
    driver: local
